// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package some_register_map_pkg;

    localparam SOME_REGISTER_MAP_DATA_WIDTH = 32;
    localparam SOME_REGISTER_MAP_MIN_ADDR_WIDTH = 14;

    typedef struct packed {
        logic [3:0] _reserved_3_0;
        logic [27:0] part_num;
    } some_register_map__chip_id__external__fields__in_t;

    typedef struct {
        logic rd_ack;
        some_register_map__chip_id__external__fields__in_t rd_data;
    } some_register_map__chip_id__external__in_t;

    typedef struct {
        logic [3:0] next;
    } link_status_field__in_t;

    typedef struct {
        link_status_field__in_t port0;
        link_status_field__in_t port1;
        link_status_field__in_t port2;
        link_status_field__in_t port3;
    } serdes_link_status_reg__in_t;

    typedef struct {
        logic [1:0] next;
    } myField_reset_0_w2__in_t;

    typedef struct {
        logic [1:0] next;
    } myField_reset_1_w2__in_t;

    typedef struct {
        logic [1:0] next;
    } myField_reset_2_w2__in_t;

    typedef struct {
        logic [1:0] next;
    } myField_reset_3_w2__in_t;

    typedef struct {
        myField_reset_0_w2__in_t data0;
        myField_reset_1_w2__in_t data1;
        myField_reset_2_w2__in_t data2;
        myField_reset_3_w2__in_t data3;
        myField_reset_0_w2__in_t data4;
        myField_reset_1_w2__in_t data5;
        myField_reset_2_w2__in_t data6;
        myField_reset_3_w2__in_t data7;
        myField_reset_0_w2__in_t data8;
        myField_reset_1_w2__in_t data9;
        myField_reset_2_w2__in_t data10;
        myField_reset_3_w2__in_t data11;
        myField_reset_0_w2__in_t data12;
        myField_reset_1_w2__in_t data13;
        myField_reset_2_w2__in_t data14;
        myField_reset_3_w2__in_t data15;
    } myReg__in_t;

    typedef struct {
        logic incr;
    } count_field_threshold_cfff_w16__in_t;

    typedef struct {
        count_field_threshold_cfff_w16__in_t port1;
        count_field_threshold_cfff_w16__in_t port0;
    } spi4_pkt_count_reg__in_t;

    typedef struct {
        logic incr;
    } count_field_w8__in_t;

    typedef struct {
        count_field_w8__in_t port3;
        count_field_w8__in_t port2;
        count_field_w8__in_t port1;
        count_field_w8__in_t port0;
    } gige_pkt_count_reg__in_t;

    typedef struct {
        logic [31:0] next;
        logic we;
    } fifoRfile__pointerReg_data_c4c0841b__data_resetsignal_7de55995__in_t;

    typedef struct {
        fifoRfile__pointerReg_data_c4c0841b__data_resetsignal_7de55995__in_t data;
    } fifoRfile__pointerReg_data_c4c0841b__in_t;

    typedef struct {
        logic [31:0] next;
        logic we;
    } fifoRfile__pointerReg__data__in_t;

    typedef struct {
        fifoRfile__pointerReg__data__in_t data;
    } fifoRfile__pointerReg__in_t;

    typedef struct {
        logic next;
    } fifoRfile__fifoStatusReg__full_reset_0_resetsignal_7de55995__in_t;

    typedef struct {
        logic next;
    } fifoRfile__fifoStatusReg__empty_reset_1__in_t;

    typedef struct {
        logic next;
    } fifoRfile__fifoStatusReg__almost_empty_reset_1__in_t;

    typedef struct {
        logic next;
    } fifoRfile__fifoStatusReg__almost_full_reset_0__in_t;

    typedef struct {
        fifoRfile__fifoStatusReg__full_reset_0_resetsignal_7de55995__in_t full;
        fifoRfile__fifoStatusReg__empty_reset_1__in_t empty;
        fifoRfile__fifoStatusReg__almost_empty_reset_1__in_t almost_empty;
        fifoRfile__fifoStatusReg__almost_full_reset_0__in_t almost_full;
    } fifoRfile__fifoStatusReg__in_t;

    typedef struct {
        fifoRfile__pointerReg_data_c4c0841b__in_t head;
        fifoRfile__pointerReg__in_t tail;
        fifoRfile__fifoStatusReg__in_t status;
    } fifoRfile__in_t;

    typedef struct {
        logic incr;
    } count_field_reset_0_w31__in_t;

    typedef struct {
        logic next;
    } vc_pkt_count_reg__active_reset_1__in_t;

    typedef struct {
        count_field_reset_0_w31__in_t vc_count;
        vc_pkt_count_reg__active_reset_1__in_t active;
    } vc_pkt_count_reg__in_t;

    typedef struct {
        logic rd_ack;
        logic [31:0] rd_data;
        logic wr_ack;
    } some_register_map__empty_addrmap__external__in_t;

    typedef struct {
        some_register_map__chip_id__external__in_t chip_id_reg;
        serdes_link_status_reg__in_t link_status;
        myReg__in_t myRegInst;
        spi4_pkt_count_reg__in_t spi4_pkt_count;
        gige_pkt_count_reg__in_t gige_pkt_count_reg;
        fifoRfile__in_t fifo_port[8];
        vc_pkt_count_reg__in_t vc_pkt_count[8][2];
        some_register_map__empty_addrmap__external__in_t empty_addrmap;
    } some_register_map__in_t;

    typedef struct {
        logic req;
        logic req_is_wr;
    } some_register_map__chip_id__external__out_t;

    typedef struct {
        logic [3:0] value;
    } link_status_field__out_t;

    typedef struct {
        link_status_field__out_t port0;
        link_status_field__out_t port1;
        link_status_field__out_t port2;
        link_status_field__out_t port3;
    } serdes_link_status_reg__out_t;

    typedef struct {
        logic [1:0] value;
    } myField_reset_0_w2__out_t;

    typedef struct {
        logic [1:0] value;
    } myField_reset_1_w2__out_t;

    typedef struct {
        logic [1:0] value;
    } myField_reset_2_w2__out_t;

    typedef struct {
        logic [1:0] value;
    } myField_reset_3_w2__out_t;

    typedef struct {
        myField_reset_0_w2__out_t data0;
        myField_reset_1_w2__out_t data1;
        myField_reset_2_w2__out_t data2;
        myField_reset_3_w2__out_t data3;
        myField_reset_0_w2__out_t data4;
        myField_reset_1_w2__out_t data5;
        myField_reset_2_w2__out_t data6;
        myField_reset_3_w2__out_t data7;
        myField_reset_0_w2__out_t data8;
        myField_reset_1_w2__out_t data9;
        myField_reset_2_w2__out_t data10;
        myField_reset_3_w2__out_t data11;
        myField_reset_0_w2__out_t data12;
        myField_reset_1_w2__out_t data13;
        myField_reset_2_w2__out_t data14;
        myField_reset_3_w2__out_t data15;
    } myReg__out_t;

    typedef struct {
        logic [15:0] value;
        logic incrthreshold;
    } count_field_threshold_cfff_w16__out_t;

    typedef struct {
        count_field_threshold_cfff_w16__out_t port1;
        count_field_threshold_cfff_w16__out_t port0;
    } spi4_pkt_count_reg__out_t;

    typedef struct {
        logic [7:0] value;
    } count_field_w8__out_t;

    typedef struct {
        count_field_w8__out_t port3;
        count_field_w8__out_t port2;
        count_field_w8__out_t port1;
        count_field_w8__out_t port0;
    } gige_pkt_count_reg__out_t;

    typedef struct {
        logic [31:0] value;
    } fifoRfile__pointerReg_data_c4c0841b__data_resetsignal_7de55995__out_t;

    typedef struct {
        fifoRfile__pointerReg_data_c4c0841b__data_resetsignal_7de55995__out_t data;
    } fifoRfile__pointerReg_data_c4c0841b__out_t;

    typedef struct {
        logic [31:0] value;
    } fifoRfile__pointerReg__data__out_t;

    typedef struct {
        fifoRfile__pointerReg__data__out_t data;
    } fifoRfile__pointerReg__out_t;

    typedef struct {
        logic value;
    } fifoRfile__fifoStatusReg__full_reset_0_resetsignal_7de55995__out_t;

    typedef struct {
        logic value;
    } fifoRfile__fifoStatusReg__empty_reset_1__out_t;

    typedef struct {
        logic value;
    } fifoRfile__fifoStatusReg__almost_empty_reset_1__out_t;

    typedef struct {
        logic value;
    } fifoRfile__fifoStatusReg__almost_full_reset_0__out_t;

    typedef struct {
        fifoRfile__fifoStatusReg__full_reset_0_resetsignal_7de55995__out_t full;
        fifoRfile__fifoStatusReg__empty_reset_1__out_t empty;
        fifoRfile__fifoStatusReg__almost_empty_reset_1__out_t almost_empty;
        fifoRfile__fifoStatusReg__almost_full_reset_0__out_t almost_full;
    } fifoRfile__fifoStatusReg__out_t;

    typedef struct {
        fifoRfile__pointerReg_data_c4c0841b__out_t head;
        fifoRfile__pointerReg__out_t tail;
        fifoRfile__fifoStatusReg__out_t status;
    } fifoRfile__out_t;

    typedef struct {
        logic [30:0] value;
    } count_field_reset_0_w31__out_t;

    typedef struct {
        logic value;
    } vc_pkt_count_reg__active_reset_1__out_t;

    typedef struct {
        count_field_reset_0_w31__out_t vc_count;
        vc_pkt_count_reg__active_reset_1__out_t active;
    } vc_pkt_count_reg__out_t;

    typedef struct {
        logic req;
        logic [1:0] addr;
        logic req_is_wr;
        logic [31:0] wr_data;
        logic [31:0] wr_biten;
    } some_register_map__empty_addrmap__external__out_t;

    typedef struct {
        some_register_map__chip_id__external__out_t chip_id_reg;
        serdes_link_status_reg__out_t link_status;
        myReg__out_t myRegInst;
        spi4_pkt_count_reg__out_t spi4_pkt_count;
        gige_pkt_count_reg__out_t gige_pkt_count_reg;
        fifoRfile__out_t fifo_port[8];
        vc_pkt_count_reg__out_t vc_pkt_count[8][2];
        some_register_map__empty_addrmap__external__out_t empty_addrmap;
    } some_register_map__out_t;

    typedef enum logic [3:0] {
        link_status_enum__not_present = 'h0,
        link_status_enum__training = 'h1,
        link_status_enum__snooze = 'h5,
        link_status_enum__sleep = 'h6,
        link_status_enum__wake = 'h7,
        link_status_enum__active = 'ha
    } link_status_enum_e;
endpackage
